// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header': string;
  'login': string;
  'login-box': string;
}
export const cssExports: CssExports;
export default cssExports;
