// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'avatar': string;
  'breadcrumb': string;
  'dashboard': string;
  'footer': string;
  'header': string;
  'logo': string;
  'main': string;
  'menu': string;
  'notification': string;
  'sider': string;
  'trigger': string;
  'user': string;
}
export const cssExports: CssExports;
export default cssExports;
