// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'dashboard': string;
  'logo': string;
  'site-layout-background': string;
  'site-layout-main': string;
  'trigger': string;
}
export const cssExports: CssExports;
export default cssExports;
